sudo: required

services:
  - docker

#before_install:
#  - docker build -t youyu/openmvg:dev .

install:
  - docker build -t youyu/openmvg:dev .

script:
  - docker run --name youyu/openmvg:dev bash -c "cd /opt/openMVG_Build/&& make test | grep "\b100% tests passed\b""
